apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-front
spec:
  replicas: 2
  selector:
    matchLabels:
      app: store-front
  template:
    metadata:
      labels:
        app: store-front
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
      - name: store-front
        image: zeelu1/store-front-25w:latest
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: store-front-config
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: store-front
spec:
  selector:
    app: store-front
  ports:
  - port: 3000
    targetPort: 3000
  type: LoadBalancer 